SELECT 
  UGU.USER_ID, 
  UGU.NICKNAME, 
  SUM(UGB.PRICE) AS TOTAL_SALES
FROM USED_GOODS_USER UGU
JOIN USED_GOODS_BOARD UGB
  ON UGU.USER_ID = UGB.WRITER_ID
WHERE UGB.STATUS = 'DONE' -- 완료된 거래만
GROUP BY UGU.USER_ID, UGU.NICKNAME
HAVING SUM(UGB.PRICE) >= 700000
ORDER BY TOTAL_SALES ASC;
